version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      PORT: 3000
      NODE_ENV: production
    restart: unless-stopped
